//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoosManagementSystem.Core.MockEnvironmentActionsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MockEnvironmentActionsService.IEnvironmentActionsService")]
    public interface IEnvironmentActionsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnvironmentActionsService/ModifyTemperature", ReplyAction="http://tempuri.org/IEnvironmentActionsService/ModifyTemperatureResponse")]
        void ModifyTemperature(System.Guid environmentId, float temperatureOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnvironmentActionsService/ModifyLuminosity", ReplyAction="http://tempuri.org/IEnvironmentActionsService/ModifyLuminosityResponse")]
        void ModifyLuminosity(System.Guid environmentId, float luminosityOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnvironmentActionsService/StartWatering", ReplyAction="http://tempuri.org/IEnvironmentActionsService/StartWateringResponse")]
        void StartWatering(System.Guid environmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnvironmentActionsService/StopWatering", ReplyAction="http://tempuri.org/IEnvironmentActionsService/StopWateringResponse")]
        void StopWatering(System.Guid environmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnvironmentActionsService/FeedingAnimal", ReplyAction="http://tempuri.org/IEnvironmentActionsService/FeedingAnimalResponse")]
        void FeedingAnimal(System.Guid environmentId, System.Guid animalId, System.Guid feedingId, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IEnvironmentActionsServiceChannel : ZoosManagementSystem.Core.MockEnvironmentActionsService.IEnvironmentActionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EnvironmentActionsServiceClient : System.ServiceModel.ClientBase<ZoosManagementSystem.Core.MockEnvironmentActionsService.IEnvironmentActionsService>, ZoosManagementSystem.Core.MockEnvironmentActionsService.IEnvironmentActionsService {
        
        public EnvironmentActionsServiceClient() {
        }
        
        public EnvironmentActionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnvironmentActionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnvironmentActionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnvironmentActionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ModifyTemperature(System.Guid environmentId, float temperatureOffset) {
            base.Channel.ModifyTemperature(environmentId, temperatureOffset);
        }
        
        public void ModifyLuminosity(System.Guid environmentId, float luminosityOffset) {
            base.Channel.ModifyLuminosity(environmentId, luminosityOffset);
        }
        
        public void StartWatering(System.Guid environmentId) {
            base.Channel.StartWatering(environmentId);
        }
        
        public void StopWatering(System.Guid environmentId) {
            base.Channel.StopWatering(environmentId);
        }
        
        public void FeedingAnimal(System.Guid environmentId, System.Guid animalId, System.Guid feedingId, int amount) {
            base.Channel.FeedingAnimal(environmentId, animalId, feedingId, amount);
        }
    }
}
